### ISSUE TITLE
How do I get the raw audio/video data?

### ISSUE THREAD

**Issue by licoba** [aws-samples/amazon-ivs-real-time-for-android-demo#11]
I don’t want to play it directly. I want to get the original audio data stream and process it myself, and then let the App play it by itself. (Should the original data be of Byte Array type or Byte Buffer type?) I have been looking for it for a long time (including  Various Demo and API documents), no corresponding method was found.

I really hope to get a quick reply! Thank you! Thank you very much!

**Comment by mboulin** [comment]
Hi. Unfortunately, the Amazon IVS Broadcast SDK does not provide a direct way to access the raw audio stream. However, you can explore using the Android `AudioRecord` class to capture the audio from the microphone and process it separately before feeding it to the IVS SDK. The raw data you will get from the mic will be in the form of byte arrays or byte buffers (depending on the method you use to read the data), which you can then process as needed through your own custom logic before feeding it to the SDK.
