### ISSUE TITLE
Help need to authenticate in to the demo app

### ISSUE THREAD

**Issue by rameshvoltella** [aws-samples/amazon-ivs-real-time-for-android-demo#8]
Hi,

We are planning to develop a module using IVS our server team has done some setup,We implemented the android sample and when we open it ask for authentication code, So we checked the document and it says 
If you are unable to scan the QR code, paste the combined Customer ID and API key in this format: {Customer ID}-{API key} when prompted in the app. For example: a1bcde23456f7g-abcDeFghIQaTbTxd0T95

So we asked the server team they gave us the following ACCESS_KEY and SECRET_KEY(the real key we have hidden below)

ACCESS_KEY= "AAAAAAA"
SECRET_KEY = "bbbbbbb"
AAAAAAAA-bbbbbbbb

when I combined these two and got an invalid code error, tell us how can we use the demo. because as we are wfh  we don't know how to implement the [Amazon IVS Real-time Serverless Demo](https://github.com/aws-samples/amazon-ivs-real-time-serverless-demo).  Our server team has implemented without  real-time-serverless-demo and its working fine for them,  but to work on Android we are very confused how to use the demo without able to enter the app, 
it will be great if you guys give a help for implementing without serverless demo.

**Comment by rameshvoltella** [comment]
@mboulin please help

**Comment by mboulin** [comment]
@rameshvoltella Thanks for your question and for testing out this demo. This demo requires a backend to function, so you will need to deploy https://github.com/aws-samples/amazon-ivs-real-time-serverless-demo in your AWS account. This backend is used to create and manage users and resources. The demo cannot function without it. 
To authenticate using the backend you've deployed, you can use the authentication code which combines two values from your backend: `domainId-apiKey`. To retrieve your API Key visit the secretUrl link shown in the "Outputs" of your stack the in the CloudFormation console, and click the "Retrieve secret value" button in the "Secret value" section.

If you are looking for a simpler demo to try out IVS real-time, take a look at https://github.com/aws-samples/amazon-ivs-real-time-streaming-android-samples .

**Comment by rameshvoltella** [comment]
@mboulin Thank you. am able to run the demo. A small help needed the apk size is big how to reduce it any gradle property needed to add for make apk smaller. like different device different apk size

**Comment by mboulin** [comment]
Unfortunately, this is outside of the scope of the demo, so we are unable to help. The IVS SDK should not increase your app size this significantly (see "Broadcast SDK Size" in https://docs.aws.amazon.com/ivs/latest/RealTimeUserGuide/release-notes.html). You could explore leveraging Play Feature Delivery to download and enable parts of your app on-demand.

If you have not already, please take a look at [AWS re:Post](https://repost.aws/) and/or post your question there, where our developer advocates and the AWS community may be able to provide additional insights.
